// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.example.test.nano;

@SuppressWarnings("hiding")
public interface TestProtos {

  public static final class Test1 extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Test1[] _emptyArray;
    public static Test1[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Test1[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 a = 1;
    public int a;

    public Test1() {
      clear();
    }

    public Test1 clear() {
      a = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.a != 0) {
        output.writeInt32(1, this.a);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.a != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.a);
      }
      return size;
    }

    @Override
    public Test1 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.a = input.readInt32();
            break;
          }
        }
      }
    }

    public static Test1 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Test1(), data);
    }

    public static Test1 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Test1().mergeFrom(input);
    }
  }

  public static final class Test2 extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Test2[] _emptyArray;
    public static Test2[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Test2[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string s = 1;
    public java.lang.String s;

    public Test2() {
      clear();
    }

    public Test2 clear() {
      s = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.s.equals("")) {
        output.writeString(1, this.s);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.s.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.s);
      }
      return size;
    }

    @Override
    public Test2 mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.s = input.readString();
            break;
          }
        }
      }
    }

    public static Test2 parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Test2(), data);
    }

    public static Test2 parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Test2().mergeFrom(input);
    }
  }

  public static final class User extends
      com.google.protobuf.nano.MessageNano {

    private static volatile User[] _emptyArray;
    public static User[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new User[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 id = 1;
    public int id;

    // optional string name = 2;
    public java.lang.String name;

    // repeated string icon_url = 3;
    public java.lang.String[] iconUrl;

    public User() {
      clear();
    }

    public User clear() {
      id = 0;
      name = "";
      iconUrl = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0) {
        output.writeInt32(1, this.id);
      }
      if (!this.name.equals("")) {
        output.writeString(2, this.name);
      }
      if (this.iconUrl != null && this.iconUrl.length > 0) {
        for (int i = 0; i < this.iconUrl.length; i++) {
          java.lang.String element = this.iconUrl[i];
          if (element != null) {
            output.writeString(3, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.id);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.name);
      }
      if (this.iconUrl != null && this.iconUrl.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.iconUrl.length; i++) {
          java.lang.String element = this.iconUrl[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public User mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt32();
            break;
          }
          case 18: {
            this.name = input.readString();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.iconUrl == null ? 0 : this.iconUrl.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.iconUrl, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.iconUrl = newArray;
            break;
          }
        }
      }
    }

    public static User parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new User(), data);
    }

    public static User parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new User().mergeFrom(input);
    }
  }

  public static final class Signed extends
      com.google.protobuf.nano.MessageNano {

    private static volatile Signed[] _emptyArray;
    public static Signed[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Signed[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 a = 1;
    public int a;

    // optional sint32 b = 2;
    public int b;

    public Signed() {
      clear();
    }

    public Signed clear() {
      a = 0;
      b = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.a != 0) {
        output.writeInt32(1, this.a);
      }
      if (this.b != 0) {
        output.writeSInt32(2, this.b);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.a != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.a);
      }
      if (this.b != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeSInt32Size(2, this.b);
      }
      return size;
    }

    @Override
    public Signed mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.a = input.readInt32();
            break;
          }
          case 16: {
            this.b = input.readSInt32();
            break;
          }
        }
      }
    }

    public static Signed parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Signed(), data);
    }

    public static Signed parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Signed().mergeFrom(input);
    }
  }

  public static final class NestTest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile NestTest[] _emptyArray;
    public static NestTest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new NestTest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .test.Test1 t = 1;
    public com.example.test.nano.TestProtos.Test1 t;

    public NestTest() {
      clear();
    }

    public NestTest clear() {
      t = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.t != null) {
        output.writeMessage(1, this.t);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.t != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.t);
      }
      return size;
    }

    @Override
    public NestTest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.t == null) {
              this.t = new com.example.test.nano.TestProtos.Test1();
            }
            input.readMessage(this.t);
            break;
          }
        }
      }
    }

    public static NestTest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new NestTest(), data);
    }

    public static NestTest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new NestTest().mergeFrom(input);
    }
  }

  public static final class RepeatedTest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RepeatedTest[] _emptyArray;
    public static RepeatedTest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RepeatedTest[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int32 a = 1;
    public int[] a;

    public RepeatedTest() {
      clear();
    }

    public RepeatedTest clear() {
      a = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.a != null && this.a.length > 0) {
        for (int i = 0; i < this.a.length; i++) {
          output.writeInt32(1, this.a[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.a != null && this.a.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.a.length; i++) {
          int element = this.a[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.a.length;
      }
      return size;
    }

    @Override
    public RepeatedTest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 8);
            int i = this.a == null ? 0 : this.a.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.a, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt32();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt32();
            this.a = newArray;
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt32();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.a == null ? 0 : this.a.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.a, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt32();
            }
            this.a = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static RepeatedTest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RepeatedTest(), data);
    }

    public static RepeatedTest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RepeatedTest().mergeFrom(input);
    }
  }

  public static final class RepeatedPackedTest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile RepeatedPackedTest[] _emptyArray;
    public static RepeatedPackedTest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RepeatedPackedTest[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int32 a = 1 [packed = true];
    public int[] a;

    public RepeatedPackedTest() {
      clear();
    }

    public RepeatedPackedTest clear() {
      a = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.a != null && this.a.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.a.length; i++) {
          int element = this.a[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        output.writeRawVarint32(10);
        output.writeRawVarint32(dataSize);
        for (int i = 0; i < this.a.length; i++) {
          output.writeInt32NoTag(this.a[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.a != null && this.a.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.a.length; i++) {
          int element = this.a[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1;
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeRawVarint32Size(dataSize);
      }
      return size;
    }

    @Override
    public RepeatedPackedTest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 8);
            int i = this.a == null ? 0 : this.a.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.a, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt32();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt32();
            this.a = newArray;
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt32();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.a == null ? 0 : this.a.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.a, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt32();
            }
            this.a = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static RepeatedPackedTest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RepeatedPackedTest(), data);
    }

    public static RepeatedPackedTest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RepeatedPackedTest().mergeFrom(input);
    }
  }

  public static final class BoolTest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile BoolTest[] _emptyArray;
    public static BoolTest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BoolTest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool a = 1;
    public boolean a;

    public BoolTest() {
      clear();
    }

    public BoolTest clear() {
      a = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.a != false) {
        output.writeBool(1, this.a);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.a != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.a);
      }
      return size;
    }

    @Override
    public BoolTest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.a = input.readBool();
            break;
          }
        }
      }
    }

    public static BoolTest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BoolTest(), data);
    }

    public static BoolTest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BoolTest().mergeFrom(input);
    }
  }

  public static final class BytesTest extends
      com.google.protobuf.nano.MessageNano {

    private static volatile BytesTest[] _emptyArray;
    public static BytesTest[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BytesTest[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bytes a = 1;
    public byte[] a;

    public BytesTest() {
      clear();
    }

    public BytesTest clear() {
      a = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!java.util.Arrays.equals(this.a, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(1, this.a);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!java.util.Arrays.equals(this.a, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(1, this.a);
      }
      return size;
    }

    @Override
    public BytesTest mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.a = input.readBytes();
            break;
          }
        }
      }
    }

    public static BytesTest parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BytesTest(), data);
    }

    public static BytesTest parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BytesTest().mergeFrom(input);
    }
  }
}
